# Example values for pg-upgrade.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
postgres:
  old: 10
  new: 12

pvcName: ex1

configMapVolume:
  name: pgo-custom-pg-config
  mountPath: /pgconf

  

